### PR TITLE
Web Demo and general inference.py

### PR DESCRIPTION
**Pull request by AK391**
added web demo on huggingface spaces with gradio and a general.py files to run a video file

### CODE REVIEW

**Comment by wmcnally** [comment]
When I try to upload my own video it does not work. It either processes the example video or does nothing. Is there a limit to the video length? What hardware is used for the app?

**Comment by AK391** [comment]
@wmcnally  https://huggingface.co/docs/hub/spaces Each Spaces environment is limited to 16GB RAM and 8 CPU cores

I tried it with other videos as well and seems to be working, how long was your video? It is better if the video is trimmed down to around 10 seconds chunks to process though otherwise it takes a while. Please let me know if there are any optimizations to help with this

Screen Shot 2021-11-19 at 12 24 56 AM

**Comment by AK391** [comment]
@wmcnally also just fixed a bug, can you please try again?

**Comment by wmcnally** [comment]
I added a link to the web demo in the readme and gave you credit.

**Pull request closed without merging**
